$correspondances = @(
	@{original = "speciaux/apos"; copies = @("speciaux/DiacriticalAcute")},
	@{original = "A"; copies = @("Α", "А")},
		@{original = "Á"; copies = @("Ά")},
		@{original = "Ä"; copies = @(<#"", #>"Ӓ")},
		@{original = "Ă"; copies = @(<#"", #>"Ӑ")},
	@{original = "Æ"; copies = @(<#"", #>"Ӕ")},
	@{original = "B"; copies = @("Β", "В")},
	@{original = "C"; copies = @("Ϲ", "С")},
	@{original = "E"; copies = @("Ε", "Е")},
		@{original = "É"; copies = @("Έ")},
		@{original = "È"; copies = @(<#"", #>"Ѐ")},
		@{original = "Ë"; copies = @(<#"", #>"Ё")},
		@{original = "Ĕ"; copies = @(<#"", #>"Ӗ")},
	@{original = "F"; copies = @("Ϝ")},
	@{original = "H"; copies = @("Η", "Н")},
	@{original = "I"; copies = @("Ι", "І", "1")},
		@{original = "Í"; copies = @("Ί")},
		@{original = "Ï"; copies = @("Ϊ", "Ї")},
	@{original = "K"; copies = @("Κ", "К")},
		@{original = "Ḱ"; copies = @(<#"", #>"Ќ")},
	@{original = "M"; copies = @("Μ", "М")},
	@{original = "N"; copies = @("Ν")},
	@{original = "O"; copies = @("Ο", "О", "0")},
		@{original = "Ó"; copies = @("Ό")},
		@{original = "Ö"; copies = @("Ӧ")},
	@{original = "P"; copies = @("Ρ", "Р")},
	@{original = "T"; copies = @("Τ", "Т")},
	@{original = "Þ"; copies = @("Ϸ")},
	@{original = "X"; copies = @("Χ", "Х")},
	@{original = "Y"; copies = @("Υ", "У")},
		@{original = "Ý"; copies = @("Ύ")},
		@{original = "Ÿ"; copies = @("Ϋ", "Ӱ")},
		@{original = "Ȳ"; copies = @(<#"", #>"Ӯ")},
	@{original = "Z"; copies = @("Ζ")},
	@{original = "Γ"; copies = @("Г")},
	@{original = "Δ"; copies = @("Д")},
	@{original = "Θ"; copies = @("Ѳ")},
	@{original = "Λ"; copies = @("Л")},
	@{original = "Π"; copies = @("П")},
	@{original = "Φ"; copies = @("Ф")},
	@{original = "З"; copies = @("3")},
	@{original = "Ч"; copies = @("4")}
)
